// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/application/services/user_service (interfaces: UserServiceProvider)
//
// Generated by this command:
//
//	mockgen -destination=mocks/user_service_mock.go -package=mocks ./internal/application/services/user_service UserServiceProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	user_service "github.com/AlexandreJSimon/hexagonal-golang-project/internal/application/services/user_service"
	domain "github.com/AlexandreJSimon/hexagonal-golang-project/internal/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockUserServiceProvider is a mock of UserServiceProvider interface.
type MockUserServiceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceProviderMockRecorder
	isgomock struct{}
}

// MockUserServiceProviderMockRecorder is the mock recorder for MockUserServiceProvider.
type MockUserServiceProviderMockRecorder struct {
	mock *MockUserServiceProvider
}

// NewMockUserServiceProvider creates a new mock instance.
func NewMockUserServiceProvider(ctrl *gomock.Controller) *MockUserServiceProvider {
	mock := &MockUserServiceProvider{ctrl: ctrl}
	mock.recorder = &MockUserServiceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceProvider) EXPECT() *MockUserServiceProviderMockRecorder {
	return m.recorder
}

// CountUsers mocks base method.
func (m *MockUserServiceProvider) CountUsers(arg0 context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockUserServiceProviderMockRecorder) CountUsers(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockUserServiceProvider)(nil).CountUsers), arg0)
}

// CreateUser mocks base method.
func (m *MockUserServiceProvider) CreateUser(arg0 context.Context, arg1 user_service.CreateUserInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceProviderMockRecorder) CreateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserServiceProvider)(nil).CreateUser), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockUserServiceProvider) DeleteUser(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServiceProviderMockRecorder) DeleteUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserServiceProvider)(nil).DeleteUser), arg0, arg1)
}

// GetUserByID mocks base method.
func (m *MockUserServiceProvider) GetUserByID(arg0 context.Context, arg1 string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserServiceProviderMockRecorder) GetUserByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserServiceProvider)(nil).GetUserByID), arg0, arg1)
}

// ListUsers mocks base method.
func (m *MockUserServiceProvider) ListUsers(arg0 context.Context, arg1, arg2 int) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUserServiceProviderMockRecorder) ListUsers(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserServiceProvider)(nil).ListUsers), arg0, arg1, arg2)
}

// UpdateUser mocks base method.
func (m *MockUserServiceProvider) UpdateUser(arg0 context.Context, arg1 string, arg2 user_service.UpdateUserInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserServiceProviderMockRecorder) UpdateUser(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserServiceProvider)(nil).UpdateUser), arg0, arg1, arg2)
}
