apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: deployment-api-patch.yaml
    target:
      kind: Deployment
      name: hexagonal-golang-api